/**
 * OLKASIS — Wallet & P2P Mock Data
 * All references use the typed TX_PREFIX system from lib/txRef.ts
 *
 * Reference anatomy: {PREFIX}{YYMMDD}{SEQ}
 * MPE = M-Pesa  BNK = Bank  CRD = Card  P2P = P2P Transfer
 * FEE = Fee     DIV = Dividend  WLT = Wallet transfer
 */

import type { Transaction, ReconciliationItem, P2PTransfer, P2PDispute } from "../types/index";

/* ─────────────────────────────────────────────────────────────
   TRANSACTIONS  (12 items to match screenshot exactly)
───────────────────────────────────────────────────────────── */
export const WALLET_TRANSACTIONS: Transaction[] = [
  {
    id:          "TXN001",
    user:        "James Mwangi",
    userId:      "USR001",
    type:        "deposit",
    method:      "M-Pesa",
    amount:      50000,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 08:00",
    ref:         "MPE240413001",
    description: "M-Pesa paybill deposit",
    category:    "mobile money",
  },
  {
    id:          "TXN002",
    user:        "David Kamau",
    userId:      "USR005",
    type:        "withdrawal",
    method:      "Bank",
    amount:      200000,
    fee:         500,
    status:      "processing",
    timestamp:   "2024-04-13 08:30",
    ref:         "BNK240413002",
    description: "Bank EFT withdrawal",
    category:    "bank transfer",
  },
  {
    id:          "TXN003",
    user:        "Amina Hassan",
    userId:      "USR002",
    type:        "deposit",
    method:      "Card",
    amount:      25000,
    fee:         250,
    status:      "completed",
    timestamp:   "2024-04-13 09:00",
    ref:         "CRD240413003",
    description: "Visa debit card deposit",
    category:    "card",
  },
  {
    id:          "TXN004",
    user:        "Grace Wanjiku",
    userId:      "USR004",
    type:        "transfer",
    method:      "P2P",
    amount:      15000,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 09:30",
    ref:         "P2P240413004",
    description: "P2P transfer to Samuel Otieno",
    category:    "p2p transfer",
  },
  {
    id:          "TXN005",
    user:        "Peter Ochieng",
    userId:      "USR003",
    type:        "withdrawal",
    method:      "M-Pesa",
    amount:      8000,
    fee:         0,
    status:      "failed",
    timestamp:   "2024-04-13 10:00",
    ref:         "MPE240413005",
    description: "M-Pesa withdrawal — insufficient balance",
    category:    "mobile money",
  },
  {
    id:          "TXN006",
    user:        "Samuel Otieno",
    userId:      "USR007",
    type:        "deposit",
    method:      "M-Pesa",
    amount:      100000,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 10:30",
    ref:         "MPE240413006",
    description: "M-Pesa paybill deposit",
    category:    "mobile money",
  },
  {
    id:          "TXN007",
    user:        "Lucy Akinyi",
    userId:      "USR008",
    type:        "withdrawal",
    method:      "Bank",
    amount:      45000,
    fee:         200,
    status:      "completed",
    timestamp:   "2024-04-13 11:00",
    ref:         "BNK240413007",
    description: "Bank EFT withdrawal",
    category:    "bank transfer",
  },
  {
    id:          "TXN008",
    user:        "James Mwangi",
    userId:      "USR001",
    type:        "fee",
    method:      "System",
    amount:      1500,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 11:15",
    ref:         "FEE240413008",
    description: "Trading commission — SCOM BUY order",
    category:    "trading fee",
  },
  {
    id:          "TXN009",
    user:        "David Kamau",
    userId:      "USR005",
    type:        "dividend",
    method:      "System",
    amount:      5000,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 11:45",
    ref:         "DIV240413009",
    description: "KCB Q1 2024 dividend payout",
    category:    "dividend income",
  },
  {
    id:          "TXN010",
    user:        "Grace Wanjiku",
    userId:      "USR004",
    type:        "deposit",
    method:      "Bank",
    amount:      150000,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 12:00",
    ref:         "BNK240413010",
    description: "Bank EFT deposit",
    category:    "bank transfer",
  },
  {
    id:          "TXN011",
    user:        "Amina Hassan",
    userId:      "USR002",
    type:        "fee",
    method:      "System",
    amount:      250,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 12:30",
    ref:         "FEE240413011",
    description: "Card processing fee — CRD240413003",
    category:    "withdrawal fee",
  },
  {
    id:          "TXN012",
    user:        "Samuel Otieno",
    userId:      "USR007",
    type:        "transfer",
    method:      "P2P",
    amount:      32500,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 13:00",
    ref:         "P2P240413012",
    description: "P2P transfer to Lucy Akinyi",
    category:    "p2p transfer",
  },
  {
    id:          "TXN013",
    user:        "Faith Njeri",
    userId:      "USR006",
    type:        "deposit",
    method:      "M-Pesa",
    amount:      12000,
    fee:         0,
    status:      "pending",
    timestamp:   "2024-04-13 13:15",
    ref:         "MPE240413013",
    description: "M-Pesa deposit — pending confirmation",
    category:    "mobile money",
  },
  {
    id:          "TXN014",
    user:        "Samuel Otieno",
    userId:      "USR007",
    type:        "transfer",
    method:      "System",
    amount:      28000,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 13:30",
    ref:         "WLT240413014",
    description: "Internal wallet transfer — check-in to investment",
    category:    "wallet transfer",
  },
  {
    id:          "TXN015",
    user:        "David Kamau",
    userId:      "USR005",
    type:        "withdrawal",
    method:      "M-Pesa",
    amount:      18500,
    fee:         0,
    status:      "completed",
    timestamp:   "2024-04-13 14:00",
    ref:         "MPE240413015",
    description: "M-Pesa withdrawal — to +254712345678",
    category:    "mobile money",
  },
];

/* ─────────────────────────────────────────────────────────────
   RECONCILIATION  (M-Pesa callbacks)
   Ref format: real M-Pesa confirmation codes (QH prefix)
───────────────────────────────────────────────────────────── */
export const RECONCILIATION_ITEMS: ReconciliationItem[] = [
  {
    id:          "REC001",
    mpesaRef:    "QHB72KN1P8",
    amount:      50000,
    phone:       "+254 712 345 678",
    timestamp:   "2024-04-13 08:00",
    status:      "matched",
    matchedTxId: "MPE240413001",
  },
  {
    id:          "REC002",
    mpesaRef:    "QHB84MN2Q9",
    amount:      25000,
    phone:       "+254 723 456 789",
    timestamp:   "2024-04-13 09:00",
    status:      "matched",
    matchedTxId: "MPE240413003",
  },
  {
    id:          "REC003",
    mpesaRef:    "QHC91NP3R2",
    amount:      12500,
    phone:       "+254 700 111 222",
    timestamp:   "2024-04-13 10:15",
    status:      "unmatched",
    discrepancy: 12500,
  },
  {
    id:          "REC004",
    mpesaRef:    "QHC03KL4S7",
    amount:      100000,
    phone:       "+254 778 901 234",
    timestamp:   "2024-04-13 10:30",
    status:      "matched",
    matchedTxId: "MPE240413006",
  },
  {
    id:          "REC005",
    mpesaRef:    "QHD14MK5T1",
    amount:      35200,
    phone:       "+254 799 333 444",
    timestamp:   "2024-04-13 11:45",
    status:      "manual_review",
    discrepancy: 200,
  },
  {
    id:          "REC006",
    mpesaRef:    "QHD25NL6U3",
    amount:      8500,
    phone:       "+254 711 555 666",
    timestamp:   "2024-04-13 12:20",
    status:      "unmatched",
    discrepancy: 8500,
  },
  {
    id:          "REC007",
    mpesaRef:    "QHE36PM7V4",
    amount:      12000,
    phone:       "+254 767 890 123",
    timestamp:   "2024-04-13 13:15",
    status:      "matched",
    matchedTxId: "MPE240413013",
  },
  {
    id:          "REC008",
    mpesaRef:    "QHE47QN8W5",
    amount:      18500,
    phone:       "+254 756 789 012",
    timestamp:   "2024-04-13 14:00",
    status:      "matched",
    matchedTxId: "MPE240413015",
  },
  {
    id:          "REC009",
    mpesaRef:    "QHF58RO9X6",
    amount:      7800,
    phone:       "+254 733 222 111",
    timestamp:   "2024-04-13 14:30",
    status:      "unmatched",
    discrepancy: 7800,
  },
  {
    id:          "REC010",
    mpesaRef:    "QHF69SP0Y7",
    amount:      45000,
    phone:       "+254 722 444 555",
    timestamp:   "2024-04-13 15:00",
    status:      "manual_review",
    discrepancy: 0,
  },
];

/* ─────────────────────────────────────────────────────────────
   P2P TRANSFERS
   Ref format: P2P + YYMMDD + SEQ
───────────────────────────────────────────────────────────── */
export const P2P_TRANSFERS: P2PTransfer[] = [
  {
    id:          "P2P001",
    sender:      "James Mwangi",
    senderId:    "USR001",
    recipient:   "Amina Hassan",
    recipientId: "USR002",
    amount:      25000,
    type:        "transfer",
    method:      "P2P",
    status:      "disputed",
    timestamp:   "2024-04-13 08:30",
    reason:      "Transfer not received",
  },
  {
    id:          "P2P002",
    sender:      "David Kamau",
    senderId:    "USR005",
    recipient:   "Peter Ochieng",
    recipientId: "USR003",
    amount:      50000,
    type:        "transfer",
    method:      "P2P",
    status:      "disputed",
    timestamp:   "2024-04-12 16:00",
    reason:      "Wrong amount sent",
  },
  {
    id:          "P2P003",
    sender:      "Grace Wanjiku",
    senderId:    "USR004",
    recipient:   "Faith Njeri",
    recipientId: "USR006",
    amount:      10000,
    type:        "transfer",
    method:      "P2P",
    status:      "completed",
    timestamp:   "2024-04-11 10:45",
  },
  {
    id:          "P2P004",
    sender:      "Samuel Otieno",
    senderId:    "USR007",
    recipient:   "Lucy Akinyi",
    recipientId: "USR008",
    amount:      32500,
    type:        "transfer",
    method:      "P2P",
    status:      "completed",
    timestamp:   "2024-04-13 09:15",
  },
  {
    id:          "P2P005",
    sender:      "Lucy Akinyi",
    senderId:    "USR008",
    recipient:   "David Kamau",
    recipientId: "USR005",
    amount:      18000,
    type:        "transfer",
    method:      "P2P",
    status:      "pending",
    timestamp:   "2024-04-13 10:45",
  },
  {
    id:          "P2P006",
    sender:      "Amina Hassan",
    senderId:    "USR002",
    recipient:   "Grace Wanjiku",
    recipientId: "USR004",
    amount:      7500,
    type:        "transfer",
    method:      "P2P",
    status:      "completed",
    timestamp:   "2024-04-13 11:20",
  },
  {
    id:          "P2P007",
    sender:      "Faith Njeri",
    senderId:    "USR006",
    recipient:   "James Mwangi",
    recipientId: "USR001",
    amount:      5000,
    type:        "transfer",
    method:      "P2P",
    status:      "failed",
    timestamp:   "2024-04-13 12:00",
  },
  {
    id:          "P2P008",
    sender:      "Samuel Otieno",
    senderId:    "USR007",
    recipient:   "Amina Hassan",
    recipientId: "USR002",
    amount:      15500,
    type:        "transfer",
    method:      "P2P",
    status:      "completed",
    timestamp:   "2024-04-13 12:45",
  },
];

/* ─────────────────────────────────────────────────────────────
   P2P DISPUTES
   Dispute IDs: DIS001, DIS002, …
───────────────────────────────────────────────────────────── */
export const P2P_DISPUTES: P2PDispute[] = [
  {
    id:         "DIS001",
    transferId: "P2P001",
    raisedBy:   "James Mwangi",
    sender:     "James Mwangi",
    receiver:   "Amina Hassan",
    amount:     25000,
    reason:     "Transfer not received",
    status:     "open",
    openedAt:   "2024-04-13 08:45",
    notes:      "",
  },
  {
    id:         "DIS002",
    transferId: "P2P002",
    raisedBy:   "David Kamau",
    sender:     "David Kamau",
    receiver:   "Peter Ochieng",
    amount:     50000,
    reason:     "Wrong amount sent",
    status:     "investigating",
    openedAt:   "2024-04-12 16:30",
    notes:      "Both parties contacted. Awaiting bank statement from sender.",
  },
  {
    id:         "DIS003",
    transferId: "P2P003",
    raisedBy:   "Grace Wanjiku",
    sender:     "Grace Wanjiku",
    receiver:   "Faith Njeri",
    amount:     10000,
    reason:     "Unauthorized transfer",
    status:     "resolved",
    openedAt:   "2024-04-11 11:00",
    notes:      "Funds reversed to sender. Receiver account flagged.",
  },
];